import Link from 'next/link';import Image from 'next/image';
import Nav from '../components/Nav';import Footer from '../components/Footer';import ThemeToggle from '../components/ThemeToggle';import ArchitectureFlow from '../components/ArchitectureFlow';import {profile,projects,career,archive} from '../data/site';
export default function Home(){return <><Nav/><main><section className="hero wrap"><div><div className="eyebrow">{profile.descriptor}</div><h1>Saurabh<br/>Jawalekar</h1><p className="heroLead">Architecting intelligent enterprise solutions — from business capability to scalable technology.</p><p className="muted">{profile.summary}</p><div className="actions"><a className="btn primary" href="#work">Explore architecture</a><a className="btn" href="/assets/Saurabh-Jawalekar-Resume.pdf">Résumé</a><a className="btn" href={profile.linkedin}>LinkedIn ↗</a></div></div><div className="portrait"><Image src="/assets/saurabh-jawalekar.png" alt="Saurabh Jawalekar" width={420} height={525} priority/><div className="badge"><b>Architecture lens</b><br/>Business · Solution · Enterprise</div></div></section>
<div className="stats wrap">{profile.stats.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div>
<section id="thinking" className="section wrap"><div className="sectionHead"><span className="eyebrow">01 / Thinking</span><div><h2>Start with the outcome.<br/>Design for what comes next.</h2><p className="muted">My architecture approach connects business intent to a governed technical foundation, then uses automation and intelligence as leverage.</p></div></div><ArchitectureFlow nodes={['Business','Architecture','Platform','Automation','Intelligence','Governance']}/></section>
<section id="work" className="section wrap"><div className="sectionHead"><span className="eyebrow">02 / Architecture portfolio</span><div><h2>Problems I like to solve.</h2><p className="muted">Representative architecture themes, deliberately separated from confidential implementation details.</p></div></div><div className="cards">{projects.map(p=><Link className="card" href={`/work/${p.slug}`} key={p.slug}><div><span className="meta">{p.label}</span><h3>{p.title}</h3><p>{p.desc}</p></div><div><div className="pills">{p.tags.map(t=><span key={t}>{t}</span>)}</div><b>Open case study →</b></div></Link>)}</div></section>
<section className="section darkPanel wrap"><div className="eyebrow">03 / Architecture model</div><h2>Capability → Process → Applications → Technology → Future State</h2><p>Architecture becomes useful when the business can see how today's landscape connects to tomorrow's decisions.</p><div className="architectureBand"><span>Capability</span><span>Process</span><span>Applications</span><span>Integration</span><span>Data</span><span>AI / Agents</span><span>Governance</span></div></section>
<section id="journey" className="section wrap"><div className="sectionHead"><span className="eyebrow">04 / Journey</span><div><h2>Three chapters.<br/>One architecture mindset.</h2><p className="muted">From SharePoint and enterprise applications to Power Platform and enterprise architecture.</p></div></div><div className="timeline">{career.map(j=><article key={j.company}><div className="period">{j.period}</div><div><h3>{j.role}</h3><b className="accent">{j.company}</b><ul>{j.items.map(i=><li key={i}>{i}</li>)}</ul></div></article>)}</div></section>
<section id="archive" className="section wrap"><div className="sectionHead"><span className="eyebrow">05 / Archive</span><div><h2>The earlier work still matters.</h2><p className="muted">The original blog shows a progression from hands-on SharePoint engineering, workflow infrastructure and migration analysis toward broader architecture and governance.</p></div></div><div className="archive">{archive.map(a=><a className="archiveItem" href={a.url} target="_blank" rel="noreferrer" key={a.title}><span>{a.year}</span><div><small>{a.type}</small><h3>{a.title}</h3><p>{a.desc}</p></div><b>↗</b></a>)}</div></section>
<section className="section wrap"><div className="cta"><div className="eyebrow">06 / Explore</div><h2>See architecture from the inside.</h2><p>Use the interactive playground to change the scenario and governance emphasis and see how the conceptual architecture shifts.</p><div className="actions"><Link className="btn primary" href="/playground">Open Architecture Playground</Link><a className="btn" href={profile.blog}>Visit old blog ↗</a></div></div></section></main><Footer/><div className="themeDock"><ThemeToggle/></div></>}
